### PR TITLE
Added eslint and fixed all errors

### LINKED ISSUE #3: Add linting!
I'm going to attempt to do this on tomorrow's live stream!

### PR DESCRIPTION
**Pull request by rhbvkleef**
Closes #3 

This PR adds eslint, and fixes the errors discovered by it. The preset used is based of the one used by the P5.js project, but has some modifications. Here is a non-exhaustive list of rules added:

- allow-parens: In arrow functions, don't add parentheses with 1 argument, always add them otherwise.
- brace-style: Opening brace on same line as relevant keyword, closing one on the same line of next relevant keyword, if there is any. (e.g. else)
- comma-dangle: In multi-line arrays, objects, ...: the last value requires a comma behind it.
- keyword-spacing: spaces around all keywords
- max-len: Maximum line-length is 100 chars
- max-params: Maximum parameters on one line is 6
- no-cond-assign: Don't allow assignment of variable inside conditional, unless an extra pair of brackets is added.
- eqeqeq: In most comparisons, require a triple equals
- no-use-before-define: Require a variable defenition to happen __before__ usage (except for functions)
- new-cap: Require class names and constructor names to be capitalized. ("Bird", not "bird")
- no-caller: Disallow `arguments.caller` and `arguments.callee`
- no-undef: Don't allow usage of undefined variables
- no-unused-vars: Don't allow defining and assigning of unused variables
- no-empty: Don't allow empty code blocks
- no-console: Don't allow console statements (console.log)
- quotes: Require single quotes
- semi: Require trailing semicolons
- space-before-blocks: Require whitespace before opening curly brace

In addition to that, "eslint:recommended" adds all rules that have a checkmark in fromt of them on
[this](https://eslint.org/docs/rules/) (https://eslint.org/docs/rules/) page and p5 and p5/dom add globals exported by P5 and P5.dom.

### CODE REVIEW

File: bird.js [hunk 1]
```diff
@@ -3,6 +3,9 @@
 // http://patreon.com/codingtrain
 // Code for: https://youtu.be/cXgA1d_E-jY
 
+/* global birdSprite */
+
+// eslint-disable-next-line no-unused-vars
```
Comment (shiffman) [inline bird.js]: Is there a way to do this in a config file? I would like the code to have minimal comments to reduce any noise as I use it as the basis for the neuro-evolution tutorials.

File: bird.js [hunk 2]
```diff
@@ -19,7 +22,13 @@ class Bird {
 
   show() {
     // draw the icon CENTERED around the X and Y coords of the bird object
-    image(this.icon, this.x - (this.width / 2), this.y - (this.height / 2), this.width, this.height);
+    image(
```
Comment (shiffman) [inline bird.js]: My preferred style is to actually leave this in one line of code. (Don't hate me!)

File: pipe.js [hunk 3]
```diff
@@ -18,9 +21,15 @@ class Pipe {
   }
 
   hits(bird) {
-    if (bird.y - (bird.height / 2) < this.top || bird.y + (bird.height / 2) > this.bottom) {
+    if (
```
Comment (shiffman) [inline pipe.js]: same here, one line.

File: sketch.js [hunk 4]
```diff
@@ -3,30 +3,37 @@
...
 var bgImg;
 var bgX = 0;
 
+// eslint-disable-next-line no-unused-vars
 function preload() {
-  pipeBodySprite = loadImage("./graphics/pipe_body.png");
-  pipePeakSprite = loadImage("./graphics/pipe_body.png");
-  birdSprite = loadImage("graphics/train.png");
-  bgImg = loadImage("graphics/background.png");
+  pipeBodySprite = loadImage('./graphics/pipe_body.png');
```
Comment (shiffman) [inline sketch.js]: yay single quotes! ❤️

File: sketch.js [hunk 5]
```diff
@@ -38,9 +45,9 @@ function draw() {
   // second copy of the image right next to it
   // once the second image gets to the 0 point, we can reset bgX to
   // 0 and go back to drawing just one image.
-  if(bgX <= -bgImg.width + width){
+  if (bgX <= -bgImg.width + width) {
```
Comment (shiffman) [inline sketch.js]: yay spaces! 😍

File: bird.js (hunk 1 above)
Comment (rhbvkleef) [reply bird.js]: I had been searching for a while, a possibility is to move everything into a global comment. I am currently looking at whether it can be hidden in the .eslintrc (at which point I'll run a base configuration for you to extend) but haven't found that yet.

File: bird.js (hunk 2 above)
Comment (rhbvkleef) [reply bird.js]: I'll adjust the eslintrc

File: bird.js (hunk 1 above)
Comment (rhbvkleef) [reply bird.js]: Apart from the fact that I think that the global asset thing is poor code-style, I don't think eslint has an easy way to configure usage checking globally. (using `"no-unused-vars": ["error", {"vars":'local"}]`) would be an option but that would miss a lot of critical linting errors. In the commit that I am pushing right now, I also replaced the disable-next-line clauses with exported clauses, as they are a bit clearer.

**Comment by rhbvkleef** [comment]
Just for the record, the rules that I aded:

- allow-parens: In arrow functions, don't add parentheses with 1 argument, always add them otherwise.
- brace-style: Opening brace on same line as relevant keyword, closing one on the same line of next relevant keyword, if there is any. (e.g. else)
- comma-dangle: In multi-line arrays, objects, ...: the last value requires a comma behind it.
- keyword-spacing: spaces around all keywords
- max-len: Maximum line-length is 100 chars
- max-params: Maximum parameters on one line is 6
- no-cond-assign: Don't allow assignment of variable inside conditional, unless an extra pair of brackets is added.
- eqeqeq: In most comparisons, require a triple equals
- no-use-before-define: Require a variable defenition to happen __before__ usage (except for functions)
- new-cap: Require class names and constructor names to be capitalized. ("Bird", not "bird")
- no-caller: Disallow `arguments.caller` and `arguments.callee`
- no-undef: Don't allow usage of undefined variables
- no-unused-vars: Don't allow defining and assigning of unused variables
- no-empty: Don't allow empty code blocks
- no-console: Don't allow console statements (console.log)
- quotes: Require single quotes
- semi: Require trailing semicolons
- space-before-blocks: Require whitespace before opening curly brace

I am missing some from the configurations that I am extending, but this is the gist of it.

**Comment by rhbvkleef** [comment]
When merging this, I recommend squashing. The reason is that this branch is build up from a lot of small commits, some of which don't really have descriptive names.

File: sketch.js (hunk 5 above)
Comment (meiamsome) [reply sketch.js]: I have personally never understood spaces after `if`/`for`/`when` - the brackets are a part of the keyword construct so why would they be separated? It would be like having function calls as `loadImage ('...');`, which, although syntactically valid, I have never seen anyone use.

(Note this isn't a request to change, I'm just wondering what the reasoning behind this is)

Comment (shiffman) [reply sketch.js]: Haha, interesting point! In my mind the space actually *distinguishes* the structure from a function call -- `if`, `for`, and `while` being special control structures? But this may just be what I tell myself to sleep at night as the missing space sends me into a panicked spiral.

Comment (rhbvkleef) [reply sketch.js]: In my reasoning, a branch construct has three or more parts, which are space separated: the keyword, the condition and the code-block. Additionally an else/elseif can be added. For me this sounds like reason to add spacing.

Comment (meiamsome) [reply sketch.js]: Ah, interesting. Those both sound like good reasoning. I think I'd be more likely to also be for that space convention if the form of `if a b else c` was allowed without the brackets (See Rust for an example when I think the syntax feels very intuitive). With them as required it feels to me like they should be attached, but thanks for telling me your thoughts!

File: bird.js (hunk 1 above)
Comment (shiffman) [reply bird.js]: I can live with the globals though I would probably prefer to put them in a config file and not have anything related to eslint in the code itself. But if having these comments is standard JavaScript practice then maybe it's good to have that here and expose viewers to this option when linting! What about also adding something that says:

```javascript
/* comments for eslint configuration */
```

There's probably a better way to phrase that. What do you think @meiamsome?

Comment (meiamsome) [reply bird.js]: We can add globals to the config file for simplicity in this case, but I am not sure what is the best course of action.

Comment (shiffman) [reply bird.js]: I'd like to try that unless anyone objects! @rhbvkleef do you want to add that to this pul request? I'm also happy to merge and refactor after if you prefer.

Comment (rhbvkleef) [reply bird.js]: Even though I personally disagree with configurations like this, I added them as you requested.

**Comment by rhbvkleef** [comment]
@shiffman Still planning on merging this or close some discussions that we had. I believe they are resolved as of my last commit.

**Comment by Versatilus** [comment]
It looks like everything is in order. Awesome!
